{% set name = "yaqd-core" %}
{% set version = "0.5.0" %}
{% set sha256 = "029745ae3965727924f4f8faf2ac8f118621451f64fc13e348a2769f28ae08c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - yaqd-base=yaqd_core._daemon:Base.main
    - yaqd-sensor=yaqd_core._sensor:Sensor.main
    - yaqd-hardware=yaqd_core._hardware._base:Hardware.main
    - yaqd-continuous-hardware=yaqd_core._hardware._continuous:ContinuousHardware.main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - appdirs
    - toml

test:
  imports:
    - yaqd_core
  commands:
    - yaqd-base -h
    - yaqd-sensor -h
    - yaqd-hardware -h
    - yaqd-continuous-hardware -h

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaqd-core-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Core python package for implementing yaq deamons, and associated utilities.  

extra:
  recipe-maintainers:
    - untzag
    - ksunden
