{% set name = "yaqd-core" %}
{% set version = "2020.7.2" %}
{% set sha256 = "0fab5f66103b8ff49c5c3f52d91d16fbc3fe759293d18159e68e16d312c08207" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - appdirs
    - toml
    - fastavro
    - flit
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - appdirs
    - toml
    - fastavro

test:
  imports:
    - yaqd_core

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Core python package for implementing yaq deamons, and associated utilities.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
