{% set name = "yaqd-core" %}
{% set version = "2020.7.1" %}
{% set sha256 = "ee88600e74f3cb1c59b82ab961eefcc92885b6bf8749dc51a4ce745ab02759ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - appdirs
    - toml
    - fastavro
    - flit
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - appdirs
    - toml
    - fastavro

test:
  imports:
    - yaqd_core

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaqd-core-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Core python package for implementing yaq deamons, and associated utilities.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
